apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}