apiVersion: apps/v1
kind: Deployment
metadata:
  name: aivar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aivar-app
  template:
    metadata:
      labels:
        app: aivar-app
    spec:
      containers:
      - name: aivar-app
        image: 287167053779.dkr.ecr.ap-south-1.amazonaws.com/build_cicd_23:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: dev
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"