apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: my-app-db-credentials
  data:
  - secretKey: DB_USERNAME
    remoteRef:
      key: devops-interview/db-secrets
      property: DB_USERNAME
  - secretKey: DB_PASSWORD
    remoteRef:
      key: devops-interview/db-secrets
      property: DB_PASSWORD
  - secretKey: JWT_SECRET
    remoteRef:
      key: devops-interview/db-secrets
      property: JWT_SECRET