apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: db-secret

  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: db-password
      property: password