apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamodb-sa
  namespace: default
  annotations:
    # This is the magic line that links K8s to AWS IAM
    eks.amazonaws.com/role-arn: arn:aws:iam::010376234075:role/IRSADynamoDBAppRole